flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Confirm')
    

class CommentForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    comment = TextAreaField('Comment', validators=[DataRequired()])
    submit = SubmitField('Add Comment')

flaskblog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flaskblog.posts.forms import PostForm, CommentForm
from flaskblog import db
from flask_login import login_required
from flaskblog.models import Post, Comment
from datetime import datetime


posts = Blueprint('posts', __name__)


comment_per_page = 5

@posts.route("/blog")
def blog():
    page = request.args.get('page', 1, type=int)
    latestpost = Post.query.order_by(Post.date_posted.desc()).first()
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=comment_per_page)
    return render_template("blog.html", posts = posts, title='Blog', latestpost=latestpost)

@posts.route("/blog/post/<int:post_id>", methods=["GET", "POST"])
def post(post_id):
    page = request.args.get('page', 1, type=int)
    blogpage = request.args.get('blogpage', 1, type=int)
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    comments = Comment.query.filter_by(post=post).order_by(Comment.date_posted.desc()).paginate(page=page, per_page=5)
    if form.validate_on_submit():
        comment = Comment(author=form.name.data, content=form.comment.data, post=post)
        db.session.add(comment)
        db.session.commit()
        flash('Comment added!', 'success')
        return redirect(url_for('posts.post', post_id=post.id, _anchor="comments"))
    return render_template('post.html', title=post.title, post=post, form=form, comments=comments, blogpage=blogpage)

@posts.route("/blog/post/<int:post_id>/edit", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.last_updated = datetime.utcnow()
        db.session.commit()
        flash('Post updated!', 'success')
        return redirect(url_for('posts.post',post_id = post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form =form, legend='Edit Post')

@posts.route("/blog/post/<int:post_id>/delete")
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post_id=post_id)
    for comment in comments:
        db.session.delete(comment)
    db.session.delete(post)
    db.session.commit()
    flash('Post has been deleted!', 'danger')
    return redirect(url_for('posts.blog'))

@posts.route("/blog/post/<int:post_id>/deletecomment")
@login_required
def delete_comment(post_id):
    comment_id = request.args.get('comment_id')
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment has been deleted!', 'danger')
    return redirect(url_for('posts.post', post_id=post_id, _anchor="comments"))



@posts.route("/blog/new_post", methods=["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data)
        db.session.add(post)
        db.session.commit()
        flash('Post created!', 'success')
        return redirect(url_for('posts.blog'))
    return render_template ('create_post.html', title = 'Create Post', form = form, legend="New Post")

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint
from flaskblog.users.forms import AdminForm
from flaskblog.models import User
from flaskblog import users, bcrypt
from flask_login import login_user, logout_user

users = Blueprint('users', __name__)

@users.route("/admin", methods=["GET", "POST"])
def admin():
    form = AdminForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            flash('You have been logged in!', 'success')
            return redirect(url_for('posts.blog'))
        else: 
            flash('Incorrect credentials', 'danger')
            return redirect(url_for('users.admin'))
    return render_template ('admin_login.html', title = 'Admin', form = form)

@users.route('/logout')
def logout():
    logout_user()
    flash('You have been logged out', 'danger')
    return redirect(url_for('main.index'))

flaskblog/templates/about.html
{% extends "layout.html"%}
{% set active_page = "about" %}
{% block content %}
<div class="container p-5 mt-3">
    <div class="row">
        <div class="col-lg-5 col-sm-12">
            <h1>About Me</h1>  
            <hr>
            <p>My name is Kendle Lam, and I'm a 17 year old high school senior. Here are some fun facts about me :) </p>
            <ul>
                <li><b>My favorite animal</b> is a dog.</li>
                <li><b>My favorite food</b> is tacos.</li>
                <li><b>I wish I could live</b> in Russia.</li>
                <li><b>Something I love to do</b> is play games with my friends.</li>
                <li><b>I would love to meet</b> Olivia Smoliga.</li>
                <li><b>My favorite song is</b> Call Me Maybe - Carly Rae Jepsen</li>
            </ul>
            <p>I'm interested in learning about you, too! Head over to my <a href="{{ url_for('posts.blog') }}">blog</a> and post a comment so I can get to know you!</p>
        </div>
        <div class="col-lg-4 col-sm-6 mb-3">
            <img class="img-fluid" alt="Kendle Lam" title="Kendle Lam" src="{{ url_for('static', filename='about_image.jpg')}}">
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card" style="border-color:#2c7cb0">
                    <h5 class="card-title text-white card-header" style="background-color: #2c7cb0;">My Socials</h5>

                <ul class="list-group list-group-flush text-black">
                    <a href="mailto:kendle.lam@gmail.com" target="_blank" rel="noopener noreferrer"><li class="list-group-item"><i class="bi bi-envelope mr-3"></i></i>Email</li></a>
                    <a href="https://www.instagram.com/kendle.lam/" target="_blank" rel="noopener noreferrer"><li class="list-group-item"><i class="bi bi-instagram mr-3"></i>Instagram</li></a>
                    <a href="https://www.facebook.com/profile.php?id=100009412276691" target="_blank" rel="noopener noreferrer"><li class="list-group-item"><i class="bi bi-facebook mr-3"></i>Facebook</li></a>
                    <a href="https://twitter.com/LamKendle" target="_blank" rel="noopener noreferrer"><li class="list-group-item"><i class="bi bi-twitter mr-3"></i>Twitter</li></a>
                    <a><li class="list-group-item"><i class="bi bi-discord mr-3"></i>Discord: babykendle#2920</li></a>
                </ul>

            </div>
        </div>
    </div>
</div>
{% endblock%}

flaskblog/templates/admin_login.html
{% extends "layout.html" %}
{% block content %}
    <div class="container pt-3">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <legend class="border-bottom mb-4">Administrator Login</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control") }}

            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control") }}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/blog.html
{% extends "layout.html"%}
{% set active_page = "blog" %}
{% block content %}
<div class="container-fluid h-100">
    <div class="row">
        <div class="col-xl-3 col-lg-4 bg-light border-right">
            <div class="sticky-top p-3">
                <div class="flex-column">
                    <div class="container">
                        <img id="circle-image" alt="Kendle Blog profile picture" title="Profile Picture" class="mx-auto d-block my-4" src="{{ url_for('static', filename='blog_profile.jpg') }}">
                        <h4 class="text-center">Kendle Lam</h4>
                        <div class="text-muted text-center">
                            {% if latestpost %}
                            {{posts.total}} Posts &#8226; Last posted {{latestpost.date_posted.strftime('%B %e, %Y')}}
                            {% else %}
                            No Posts Yet :(
                            {% endif %}
                            
                        </div>
                        <div class="py-4 px-2">
                            <p>Hi everyone, welcome to my blog!</p> 
                            <p>I've never really blogged before so don't expect polished articles!</p>
                            <p>Here I post about random
                                stuff from League guides (I'm qualified as a prestigious Platinum player) to my personal thoughts. If you have time drop a comment on a post! </p> 
                            <p>Happy reading!</p>
                        </div>
                    </div>
                    
                </div>
                
            </div>
        </div>
        <div class="col-xl-9 col-lg-8 px-3">
            <a id="blogposts"></a>
            {% if current_user.is_authenticated %}
            <a class="btn btn-info mt-3 btn-block btn-lg" href="{{ url_for('posts.new_post') }}"><i class="bi bi-file-earmark-post"></i> New Post</a>
            {% endif %}
            {% for post in posts.items %}
            <a id="{{ post.id }}"></a>
            <div class="card my-3 flex-row">
                <div class="w-100">
                    <h3 class="card-title card-header">{{ post.title }}</h3>
                    <div class="card-body">
                        <p class="card-subtitle text-muted">{{ post.date_posted.strftime('%B %e, %Y') }}
                            {% if post.date_posted.strftime('%B %e, %Y') != post.last_updated.strftime('%B %e, %Y') %} |
                            <span> Last Updated on {{ post.last_updated.strftime('%B %e, %Y')}}</span>
                            {% endif %}
    
                        </p>
                        <div class="card-text mt-3 blog-text" >{{ post.content|safe }}</div>
                    </div>  
                </div>

               

                <a  href="{{ url_for('posts.post', post_id=post.id, blogpage=posts.page) }}" class="ml-auto">
                    <button class="btn rounded-1 h-100 stretched-link" style="background-color: #2c7cb0;">
                        <i class="bi bi-arrow-right text-white"></i>
                    </button>
                    
                </a>       
            </div>
            {% endfor %}
            <div class="d-flex justify-content-between">
                {% if posts.page != 1 %}
                <a class="btn btn-info mb-3" href="{{ url_for('posts.blog', page=posts.page-1, _anchor='blogposts')}}"><i class="bi bi-arrow-left"></i></a>
                {% else %}
                <a class="btn btn-info mb-3 invisible" href="#"><i class="bi bi-arrow-left"></i></a>
                {% endif %}
                <h4>Page {{posts.page}}/{{posts.pages}}</h4>
                {% if posts.page != posts.pages %}
                <a class="btn btn-info mb-3" href="{{ url_for('posts.blog', page=posts.page+1, _anchor='blogposts')}}"><i class="bi bi-arrow-right"></i></a>
                {% else %}
                <a class="btn btn-info mb-3 invisible" href="#"><i class="bi bi-arrow-right"></i></a>
                {% endif %}
                
            </div>
        </div>
    </div>
   
</div>


{% endblock%}

flaskblog/templates/contact.html
{% extends "layout.html"%}
{% set active_page = "contact" %}
{% block content %}

<div class="container p-3">
    <legend class="border-bottom mb-3">Contact Kendle!</legend>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        
        <div class ="form-group">
            {{ form.name.label }}
            {{ form.name(class="form-control") }}
        </div>      
        <div class ="form-group">
            {{ form.subject.label }}
            {{ form.subject(class="form-control") }}
        </div>     
        <div class ="form-group">
            {{ form.email.label }}
            {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
            {% else %}
                {{ form.email(class="form-control") }}
            {% endif %}
        </div>     
        <div class ="form-group">
            {{ form.message.label }}
            {{ form.message(class="form-control", rows=30) }}
        </div>    
        <div class ="form-group">
            {{ form.recaptcha}}
        </div>    
        <div class ="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>        
    </form> 
</div>

<script src="https://cdn.tiny.cloud/1/x5xedkas9j5vinilvzforqrib3msdt54bsjq3r5x5hr2z53f/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script type="text/javascript">
     tinymce.init({
  selector: '#message',
  height: 500,
  menubar: false,
  plugins: [
    'advlist autolink lists link image charmap print preview anchor',
    'searchreplace visualblocks code fullscreen',
    'insertdatetime media table paste code help wordcount'
  ],
  toolbar: 'undo redo | formatselect | ' +
  'bold italic backcolor | alignleft aligncenter ' +
  'alignright alignjustify | bullist numlist outdent indent | ' +
  'removeformat | help',
  content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }',
  setup: function (editor) {
    editor.on('change', function () {
        tinymce.triggerSave();
    });
}
});
</script>

{% endblock%}

flaskblog/templates/create_post.html
{% extends "layout.html"%}
{% set active_page = "blog" %}
{% block content %}

<div class="container my-3">
    <a class="btn bg-light my-3" href=javascript:history.back()><i class="bi bi-arrow-left"></i><span class="ml-2"> Back</span></a>
    <legend class="border-bottom mb-3">{{ legend }}</legend>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <div class ="form-group">
            {{ form.title.label }}
            {{ form.title(class="form-control") }}
        </div>      
        <div class ="form-group">
            {{ form.content.label }}
            {{ form.content(class="form-control", rows=30) }}
        </div>        
        <div class ="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>        
    </form> 
</div>

<script src="https://cdn.tiny.cloud/1/x5xedkas9j5vinilvzforqrib3msdt54bsjq3r5x5hr2z53f/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script type="text/javascript">
     tinymce.init({
  selector: '#content',
  plugins: 'print preview paste importcss searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern noneditable help charmap quickbars emoticons',
  menubar: 'file edit view insert format tools table tc help',
  toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist',
  /* enable title field in the Image dialog*/
  image_title: true,
  /* enable automatic uploads of images represented by blob or data URIs*/
  automatic_uploads: true,
  /*
    URL of our upload handler (for more details check: https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_url)
    images_upload_url: 'postAcceptor.php',
    here we add custom filepicker only to Image dialog
  */
  file_picker_types: 'image',
  image_dimensions: false,
  image_class_list: [
            {title: 'Responsive', value: 'img-fluid'}
        ],
  /* and here's our custom image picker*/
  file_picker_callback: function (cb, value, meta) {
    var input = document.createElement('input');
    input.setAttribute('type', 'file');
    input.setAttribute('accept', 'image/*');

    /*
      Note: In modern browsers input[type="file"] is functional without
      even adding it to the DOM, but that might not be the case in some older
      or quirky browsers like IE, so you might want to add it to the DOM
      just in case, and visually hide it. And do not forget do remove it
      once you do not need it anymore.
    */

    input.onchange = function () {
      var file = this.files[0];

      var reader = new FileReader();
      reader.onload = function () {
        /*
          Note: Now we need to register the blob in TinyMCEs image blob
          registry. In the next release this part hopefully won't be
          necessary, as we are looking to handle it internally.
        */
        var id = 'blobid' + (new Date()).getTime();
        var blobCache =  tinymce.activeEditor.editorUpload.blobCache;
        var base64 = reader.result.split(',')[1];
        var blobInfo = blobCache.create(id, file, base64);
        blobCache.add(blobInfo);

        /* call the callback and populate the Title field with the file name */
        cb(blobInfo.blobUri(), { title: file.name });
      };
      reader.readAsDataURL(file);
    };

    input.click();
  },
    setup: function (editor) {
    editor.on('change', function () {
        tinymce.triggerSave();
    });

}
});
</script>


{% endblock%}

flaskblog/templates/index.html
{% extends "layout.html"%}
{% set active_page = "index" %}
{% block content %}
    <div class="container p-5">
        <div class="row">
            <div class="col-md-7 align-self-center">
                <h1 class="py-3">Hi there, I'm Kendle! &#128075</h1>  
                <p>Welcome to my website! I'm an average high school boy interested in computer science.</p>
                <p>In my free time, you'll find me playing League of Legends, reading political and economic articles, or playing piano. Nice to meet you! </p>    
                <p>Check out my <a href="{{ url_for('posts.blog') }}">blog</a> if you're interested in learning more about me :)</p>
            </div>
            <div class="col-md-5 py-5 align-self-center">
                <img class="img-fluid" alt="Kendle Lam" title="Kendle Lam"src="{{ url_for('static', filename='homepic.jpg') }}">
            </div>
        </div>
    </div>

{% endblock%}

flaskblog/templates/layout.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    {% if title %}
    <title>{{ title }} | Kendle Lam</title>
    {% else %}
    <title>Kendle Lam</title>
    {% endif %}
</head>

<body>

    {% set navigation_bar = [
        ('main.index', 'index', 'Home'),
        ('main.about', 'about', 'About'),
        ('main.contact', 'contact', 'Contact'),
        ('posts.blog', 'blog', 'Blog')
        
    ] -%}
    
    {% set active_page = active_page|default('index') -%}
    
    <div class="header">
        <h1>Kendle Lam</h1>
    </div>
    <nav class="navbar navbar-expand-lg p-2 border-bottom navbar-dark" style="background-color:rgb(0, 106, 199)">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="p-2 collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav" >
                {% for href, id, caption in navigation_bar %}
                {% if id == active_page %} 
                <li class="nav-item mx-3 border-bottom"><a class="nav-link text-white" href="{{ url_for(href) }}">{{ caption|e }}</a></li>
                {% else %}
                <li class="nav-item mx-3"><a class="nav-link" href="{{ url_for(href) }}">{{ caption|e }}</a></li>
                {% endif%}
                {% endfor %} 
            </ul>
            {% if current_user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item mx-3 align-self-right"><a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
            </ul>
                
            {% endif %}
          </div>
        
    </nav>
    
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category,message in messages %}
        <div class="alert alert-{{ category }}">
            {{ message }} 
        </div>
        {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
    

</body>

</html>

flaskblog/templates/post.html
{% extends "layout.html"%}
{% set active_page = "blog" %}
{% block content %}
<div class="bg-light">
    
    <div class="container pb-5">
        <span>
            <a class="btn bg-light my-3" href="{{ url_for('posts.blog', page=blogpage, _anchor= post.id )}}"><i class="bi bi-arrow-left"></i><span class="ml-2"> Back to Blog</span></a>
        </span>
        {% if current_user.is_authenticated %}
                    <div class="p-2">
                        <a class="btn btn-outline-secondary btn-block" href="{{ url_for('posts.update_post', post_id=post.id) }}" role="button"><i class="bi bi-pencil-square"></i> Edit Post</a>
                        <button type="button " class="btn btn-outline-danger btn-block" data-toggle="modal" data-target="#deletePostModal">
                            <i class="bi bi-trash"></i> Delete Post
                          </button>
                    </div>
                {% endif %}
        <div class="card">
            <div class="card-body">
                    <h1 class="card-title">{{ post.title }}</h1>

                    <h5 class="card-subtitle text-muted">{{ post.date_posted.strftime('%B %e, %Y') }}</h5>
                    <div class="card-text pt-3">{{ post.content|safe }}</div>
                
                
            </div>
            
            
        </div>
    </div>

    <div class="container">
        <a id="comments"></a>
        <legend class="border-bottom mb-3">Comments ({{comments.total}})</legend>
        {% for comment in comments.items %}
        <div class="card my-3 ">
            <div class="card-body">
                <div class=" flex-row d-flex justify-content-between">
                    <h5 class="card-title text-truncate">{{ comment.author }}<span class="text-muted"> on {{ comment.date_posted.strftime('%B %e, %Y') }} at {{ comment.date_posted.strftime('%#I:%M %p') }} UTC:</span></h5>
                    {% if current_user.is_authenticated %}
                    <a class="btn btn-outline-danger" href="{{ url_for('posts.delete_comment', post_id=post.id, comment_id=comment.id) }}" role="button"><i class="bi bi-trash"></i></a>
                    {% endif %}
                </div>
                <div class="card-text mt-1" >{{ comment.content }}</div>
                
            </div>     
        </div>
        {% endfor %}
        {% if comments.total > 0%}
        <div class="d-flex justify-content-between py-3">
            {% if comments.page != 1 %}
            <a class="btn btn-info mb-3" href="{{ url_for('posts.post', post_id=post.id, page=comments.page-1, _anchor='comments', blogpage=blogpage)}}"><i class="bi bi-arrow-left"></i></a>
            {% else %}
            <a class="btn btn-info mb-3 invisible" href="#"><i class="bi bi-arrow-left"></i></a>
            {% endif %}
            <h5>Page {{comments.page}}/{{comments.pages}}</h5>
            {% if comments.page != comments.pages %}
            <a class="btn btn-info mb-3" href="{{ url_for('posts.post', post_id=post.id, page=comments.page+1, _anchor='comments', blogpage=blogpage)}}"><i class="bi bi-arrow-right"></i></a>
            {% else %}
            <a class="btn btn-info mb-3 invisible" href="#"><i class="bi bi-arrow-right"></i></a>
            {% endif %}
            
        </div>
        {% endif %}
        <legend class="border-bottom mb-3">Add a Comment</legend>
        <form class="pb-3" method="POST" action="">
            {{ form.csrf_token }}
            <div class ="form-group">
                {{ form.name.label }}
                {{ form.name(class="form-control") }}
            </div>       
            <div class ="form-group">
                {{ form.comment.label }}
                {{ form.comment(class="form-control", rows=5) }}
            </div>    
            <div class ="form-group">
                {{ form.submit(class="btn btn-secondary") }}
            </div>        
        </form> 
    </div>
    
</div>

<div class="modal" id="deletePostModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered " role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Notice</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this post?</p>
          <p>"{{ post.title }}"</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <a class="btn btn-danger" href="{{ url_for('posts.delete_post', post_id=post.id) }}" role="button">Delete</a>
        </div>
      </div>
    </div>
</div>


{% endblock%}